version: "3.7"
services:
  frontend:
    container_name: my-front
    # image: docker-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app

  backend:
    container_name: my-back
    # image: flask-dev
    build:
      context: backend
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/www